# Form implementation generated from reading ui file 'dangnhap.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def open_dangki(self):
        from dangki import Ui_MainWindow_2  # CHUYỂN VÀO TRONG HÀM
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_2()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_trangchu(self):
        email = self.txtEmail.text()
        password = self.txtPassword.text()
        if email == 'Admin' and password == 'Admin':
         from trangchu import CarManager
         self.window = CarManager()
         self.window.show()
        else:
         QtWidgets.QMessageBox.warning(None, "Lỗi", "Email hoặc mật khẩu không đúng!")
    
    
    
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 699)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setStyleSheet("background-color:grey;\\nborder-radius: 15px;")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 120))
        self.widget_4.setStyleSheet("background-color: white;\n"
"border-radius: 15px;")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_2.addWidget(self.widget_6)
        self.label = QtWidgets.QLabel(parent=self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(27)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: light blue;\n"
"border-radius: 15px;")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_2.addWidget(self.widget_7)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_5.setStyleSheet("background-color: white;\n"
"border-radius: 15px;")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblEmail = QtWidgets.QLabel(parent=self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblEmail.setFont(font)
        self.lblEmail.setObjectName("lblEmail")
        self.verticalLayout_2.addWidget(self.lblEmail)
        self.txtEmail = QtWidgets.QLineEdit(parent=self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtEmail.setFont(font)
        self.txtEmail.setStyleSheet("background-color: #ECE3D2;\\ncolor: #356A9C;\\nfont: 12pt \"Segoe UI\";\\nborder-radius: 15px;\\npadding-left: 5px;")
        self.txtEmail.setObjectName("txtEmail")
        self.verticalLayout_2.addWidget(self.txtEmail)  
        self.lblas = QtWidgets.QLabel(parent=self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.lblas.setFont(font)
        self.lblas.setObjectName("lblas")
        self.verticalLayout_2.addWidget(self.lblas)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.widget_5)    
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.txtPassword.setFont(font)
        self.txtPassword.setStyleSheet("background-color: #ECE3D2;\\ncolor: #356A9C;\\nfont: 12pt \"Segoe UI\";\\nborder-radius: 15px;\\npadding-left: 5px;")
        self.txtPassword.setObjectName("txtPassword")
        self.verticalLayout_2.addWidget(self.txtPassword)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget_5)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.btn_register = QtWidgets.QPushButton(parent=self.widget_5,clicked=lambda:self.open_dangki())
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_register.setFont(font)
        self.btn_register.setIconSize(QtCore.QSize(20, 20))
        self.btn_register.setObjectName("btn_register")
        self.verticalLayout_2.addWidget(self.btn_register)
        self.btn_login = QtWidgets.QPushButton(parent=self.widget_5, clicked=self.open_trangchu)
        self.btn_login.setStyleSheet("border-radius: 15px;\n"
"font: 600 16pt \"Bahnschrift\";\n"
"background-color: #356a9c;\n"
"color: #F8F2EC;\n"
"")
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout_2.addWidget(self.btn_login)
        self.verticalLayout.addWidget(self.widget_5)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Đăng nhập"))
        self.lblEmail.setText(_translate("MainWindow", "Email"))
        self.lblas.setText(_translate("MainWindow", "Mật khẩu"))
        self.btn_register.setText(_translate("MainWindow", "Đăng kí!"))
        self.btn_login.setText(_translate("MainWindow", "Đăng nhập"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())


        